development:
  adapter: postgresql
  encoding: unicode
  database: face_development
  pool: 5
  timeout: 5000
  username: paniotov
  password: a21041992

test:
  adapter: postgresql
  encoding: unicode
  database: face_test
  pool: 5
  timeout: 5000
  username: paniotov
  password: a21041992

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: face_production
  pool:     5
  username: paniotov
  password: a21041992
  template: template0